version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: postgres
    restart: always
    volumes:
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Julinho2
      POSTGRES_DB: plants-api

volumes:
  postgres-disk: