version: '3'

services:
  streaming:
    image: postgres
    ports:
      - '5432:5432'
    container_name: streaming
    restart: always
    volumes:
      - streaming-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: streaming-api

volumes:
  streaming-disk: